---

- name: Include AWX/Automation Controller master token from awx_tokens.yml
  delegate_to: localhost
  include_vars:
    file: /tmp/awx/tokens.yml
  no_log: True

- name: Create a AWX/Automation Controller session token for executing AWX modules
  awx.awx.tower_token:
    description: 'AWX/Automation Controller Session Token'
    scope: "write"
    state: present
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ master_token }}"
    validate_certs: yes
  register: awx_session_token

- name: Remove the default 'Demo Job Template'
  awx.awx.tower_job_template:
    name: "Demo Job Template"
    job_type: run
    project: "Demo Project"
    playbook: hello_world.yml
    state: absent
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes

- name: Remove the default 'Demo Project'
  awx.awx.tower_project:
    name: "Demo Project"
    organization: "Default"
    state: absent
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  ignore_errors: yes

- name: Remove the default 'Demo Inventory'
  awx.awx.tower_inventory:
    name: "Demo Inventory"
    organization: "Default"
    state: absent
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  ignore_errors: yes

- name: Remove the default 'Demo Credential' credential
  awx.awx.tower_credential:
    name: "Demo Credential"
    user: "admin"
    credential_type: ssh
    state: absent
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  ignore_errors: yes

- name: Remove the default 'Default' organisation
  awx.awx.tower_organization:
    name: "Default"
    state: absent
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  ignore_errors: yes