---

- name: Collect timezone of AWX/Automation Controller server (Debian and derivatives only)
  command: cat /etc/timezone
  register: timezone_output

- name: Create an rrule string for the 'Deploy All Servers'
  set_fact:
    rrule_line_update: "DTSTART;TZID={{ timezone_output.stdout }}:{{ update_schedule_start }} RRULE:FREQ={{ update_schedule_frequency }};INTERVAL={{ update_schedule_interval }}"

- name: Build a schedule for 'Deploy All Servers' job template
  awx.awx.tower_schedule:
    name: "Deploy All Servers"
    enabled: yes
    state: present
    unified_job_template: "Deploy All Servers"
    extra_data: "{{ lookup('file', '{{ role_path }}/extra-vars/update_all.json') }}"
    rrule: "{{ rrule_line_update }}"
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes

- name: Delete the AWX/Automation Controller session token for executing modules
  awx.awx.tower_token:
    description: 'AWX/Automation Controller Session Token'
    scope: "write"
    state: absent
    existing_token_id: "{{ awx_session_token.ansible_facts.tower_token.id }}"
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes