---

- name: Ensure /root/k3s folder exists
  file:
    path: /root/k3s
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Install the k3s install.sh script
  copy:
    src: '{{ role_path }}/scripts/k3s/install.sh'
    dest: /root/k3s/install.sh
    owner: root
    group: root
    mode: '0700'

- name: Run the k3s install.sh script
  shell: |
      sh /root/k3s/install.sh --write-kubeconfig-mode 644

- name: Ensure kube directory exists
  file:
    path: /root/.kube
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Set up kubeconfig
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: '0600'